version: '3'
services:
  db:
    build: './database'
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    container_name: postgres-container
    ports:
      - '5432:5432'
    expose:
      - '5432'

# volumes:
#   postgres-data:
# networks:
#   app-network:
#     driver: bridge